import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  // Manually defined sidebar to control order and capitalization
  tutorialSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Architecture',
      items: [
        {
          type: 'autogenerated',
          dirName: 'architecture',
        },
      ],
    },
    {
      type: 'category',
      label: 'Backend',
      items: [
        {
          type: 'autogenerated',
          dirName: 'backend',
        },
      ],
    },
    {
      type: 'category',
      label: 'Frontend',
      items: [
        {
          type: 'autogenerated',
          dirName: 'frontend',
        },
      ],
    },
    {
      type: 'category',
      label: 'Database',
      items: [
        {
          type: 'autogenerated',
          dirName: 'database',
        },
      ],
    },
    {
      type: 'category',
      label: 'API',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: 'DevOps',
      items: [
        {
          type: 'autogenerated',
          dirName: 'devops',
        },
      ],
    },
  ],
};

export default sidebars;
